Hualca lizbeth
Alpha-Code-tis/taller360 pull request #23
Opened 2024-12-09 23:09 UTC by LizbethHY

validacion sobre grupo, correcta creacion de docente, correccion de sprints en planilla de notas y uso de variables locales

2024-12-11 09:27 UTC, c4str0-c137 requested changes
Resolver conflictos en frontend EvaluationForm 
![image](https://github.com/user-attachments/assets/f929f7e4-5d37-4ae0-8d14-124c1bb6df94)

2024-12-11 23:55 UTC, RocioDelAlb4 approved these changes

2024-12-12 01:59 UTC, c4str0-c137 approved these changes

2024-12-12 13:58 UTC, YesicaSc2 approved these changes

2024-12-12 19:28 UTC, merged